version: '3'
services:
  front-end:
    build:
      dockerfile: test.dockerfile
      context: ./iot-app/
    image: guilhermeroque/iot-app-test
    environment:
      - REACT_APP_IDENTITY_SERVER=http://localhost:3000
    ports:
      - "8080:3000"
    volumes:
      - ./iot-app/src:/root/src
    depends_on:
      - identity-service

  identity-service:
    build:
      dockerfile: test.dockerfile
      context: ./auth-service/
    image: guilhermeroque/auth-service-test
    environment:
      - DB_URL=mongodb://mongo/
      - DB_NAME=auth-service
      - DB_USERNAME=lorawanMgnt-admin
      - DB_PASSWORD=lorawanMgnt-admin
      - DB_HOST=mongo
      - SERVER_PORT=3000
      - SWAGGER_HOST=localhost:3000
    volumes:
      - ./auth-service/src:/root/src
    ports:
      - "3000:3000"
    depends_on:
      - mongo

  mongo:
    image: mongo:5.0-focal
    environment:
      - MONGO_INITDB_ROOT_USERNAME=lorawanMgnt-admin
      - MONGO_INITDB_ROOT_PASSWORD=lorawanMgnt-admin
    ports:
      - "27017:27017"


  telegraf:
    image: telegraf:1.23
    environment:
      - USER=lorawanMgnt-admin
      - INFLUX_URL=influxdb
      - INFLUX_SKIP_DATABASE_CREATION=true
      - INFLUX_PASSWORD=lorawanMgnt-admin
      - INFLUX_BUCKET=lorawanMgnt-bucket
      - INFLUX_ORG=lorawanMgnt-org
      - INFLUX_TOKEN=8s7p1LY3SSGWX-yH2UAKPKABloCcH2s3MwWr71sKRsCBYbloJn_iYP70-ZUhOXi7870CYesIT5SNeYHsxFU4rQ==
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf
    depends_on:
      - influxdb



  influxdb:
    image: influxdb:2.3.0
    environment: 
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=lorawanMgnt-admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=lorawanMgnt-admin
      - DOCKER_INFLUXDB_INIT_ORG=lorawanMgnt-org
      - DOCKER_INFLUXDB_INIT_BUCKET=lorawanMgnt-bucket
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=8s7p1LY3SSGWX-yH2UAKPKABloCcH2s3MwWr71sKRsCBYbloJn_iYP70-ZUhOXi7870CYesIT5SNeYHsxFU4rQ==
    volumes:
      - ./influxdb2:/var/lib/influxdb2:rw
    ports:
      - "8086:8086"


