version: '3'
services:
  api-gateway:
    build:
      dockerfile: Dockerfile
      context: ./api-gateway-auth/
    image: guilhermeroque/api-gateway-auth
    environment:
      - APP_ENV=production
      - IDENTITY_SERVICE=http://identity-service:3000
      - FRONT_END=http://front-end:3000
      - APP_MGR= http://device-mgnt:3000
      - ACCESS_SECRET=/root/access-token.pub
      - REFRESH_SECRET=/root/refresh-token.pub
      - REDIS_URL=redis://redis:6379
      - INFLUX_URL=http://influxdb:8086
      - INFLUX_BUCKET=lorawan-bucket
      - INFLUX_TOKEN=8s7p1LY3SSGWX-yH2UAKPKABloCcH2s3MwWr71sKRsCBYbloJn_iYP70-ZUhOXi7870CYesIT5SNeYHsxFU4rQ==
      - DATA_ANALYSER=http://data-analyser:5555
      - CLIENT_ENTRYPOINT_URL=http://front-end:3000

    volumes:
      - ./api-gateway-auth/src:/root/src
    ports:
      - 8000:3000
    depends_on:
      - redis
      - identity-service
      - device-mgnt
      - front-end
      - data-analyser
      - influxdb

  front-end:
    build:
      dockerfile: test.dockerfile
      context: ./iot-app/
    image: guilhermeroque/iot-app-test
    environment:
      - REACT_APP_API_GATEWAY=http://localhost:8000/api
      - REACT_APP_APP_ENV=production
    ports:
      - "8080:3000"
    volumes:
      - ./iot-app/src:/root/src

  identity-service:
    build:
      dockerfile: Dockerfile
      context: ./auth-service/
    image: guilhermeroque/auth-service-test
    environment:
      - APP_ENV=production
      - DB_URL=mongodb://mongo/
      - DB_NAME=identity-service
      - DB_USERNAME=lorawan-user
      - DB_PASSWORD=lorawan-password
      - DB_HOST=mongo
      - SERVER_PORT=3000
      - SWAGGER_HOST=localhost:3000
      - ACCESS_SECRET=/root/access-token.key
      - REFRESH_SECRET=/root/refresh-token.key
      - ACCESS_TIMEOUT=300s
      - REFRESH_TIMEOUT=1d
      - SECRET=29a2ac06-d5cb-4fd3-85ee-00d42234d41d
    volumes:
      - ./auth-service/src:/root/src
    ports:
      - "3000:3000"
    depends_on:
      - mongo

  device-mgnt:
    build:
      dockerfile: Dockerfile
      context: ./device-mgnt
    image: guilhermeroque/device-mgnt
    environment:
      - APP_ENV=production
      - BROKER_TTN=eu1.cloud.thethings.network
      - USER_TTN=lorawan-mgnt
      - PORT_TTN=1883
      - PASSWORD_TTN=NNSXS.4UEYPLW2ZI765HTJSQSKEUSV3XCZ3UBTFRF3XNA.JR3QGULLZVMS5HYA2AHY47XRJQTDKCJ3IPTLRLJ7I7UO2K2QPZAA
      - DB_URL=mongodb://mongo/
      - DB_NAME=lorawan-app-mgr
      - DB_USERNAME=lorawan-user
      - DB_PASSWORD=lorawan-password
      - DB_HOST=mongo
      - SERVER_PORT=3000
      - WS_PORT=5000
    ports:
      - "3333:3000"
      - "5000:5000"
    depends_on:
      - influxdb
      - mongo      
    volumes:
      - ./device-mgnt/src:/root/src

  data-analyser:
    build:
      dockerfile: Dockerfile
      context: ./data-analyser
    image: guilhermeroque/data-analyser
    environment:
      - INFLUX_URL=http://influxdb:8086
      - INFLUX_BUCKET=lorawan-bucket
      - INFLUX_TOKEN=8s7p1LY3SSGWX-yH2UAKPKABloCcH2s3MwWr71sKRsCBYbloJn_iYP70-ZUhOXi7870CYesIT5SNeYHsxFU4rQ==
    depends_on:
      - influxdb
    ports:
      - "5555:5555"

  device-proxy:
    build:
      dockerfile: Dockerfile
      context: ./device-proxy
    image: guilhermeroque/device-proxy
    environment:
      - APP_ENV=production
      - TOKEN_INFLUX=8s7p1LY3SSGWX-yH2UAKPKABloCcH2s3MwWr71sKRsCBYbloJn_iYP70-ZUhOXi7870CYesIT5SNeYHsxFU4rQ==
      - BUCKET_INFLUX=lorawan-bucket
      - ORGANIZATION_INFLUX=lorawan-org
      - BASE_URL_INFLUX=http://influxdb:8086
      - BROKER_TTN=eu1.cloud.thethings.network
      - PORT_TTN=1883
      - APP_MGR=device-mgnt:5000
    depends_on:
      - influxdb
      - device-mgnt

  redis: 
    image: redis:7.0.4
    ports:
      - "6379:6379"

  mongo:
    image: mongo:5.0-focal
    environment:
      - MONGO_INITDB_ROOT_USERNAME=lorawan-user
      - MONGO_INITDB_ROOT_PASSWORD=lorawan-password
    ports:
      - "27017:27017"

  influxdb:
    image: influxdb:2.3.0
    environment: 
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=lorawan-user
      - DOCKER_INFLUXDB_INIT_PASSWORD=lorawan-password
      - DOCKER_INFLUXDB_INIT_ORG=lorawan-org
      - DOCKER_INFLUXDB_INIT_BUCKET=lorawan-bucket
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=8s7p1LY3SSGWX-yH2UAKPKABloCcH2s3MwWr71sKRsCBYbloJn_iYP70-ZUhOXi7870CYesIT5SNeYHsxFU4rQ==
    volumes:
      - ./influxdb2:/var/lib/influxdb2:rw
    ports:
      - "8086:8086"


