version: '3'
services:
  api-gateway:
    build:
      dockerfile: test.dockerfile
      context: ./api-gateway-auth/
    image: guilhermeroque/api-gateway-auth
    environment:
      - IDENTITY_SERVICE=http://identity-service:3000
      - FRONT_END=http://front-end:3000
      - DEVICE_MGNT= http://device-mgnt:3000
      - ACCESS_TOKEN_SECRET=45d239dd6d20d8e4c5919079a40e5ea6cf8d9ab0
      - REFRESH_TOKEN_SECRET=45d239dd6d20d8e4c5919079a40e5ea6cf8d9ab0
      - REDIS_URL=redis://redis:6379
      - APP_ENV=local
      - INFLUX_URL=http://influxdb:8086
      - INFLUX_TOKEN=8s7p1LY3SSGWX-yH2UAKPKABloCcH2s3MwWr71sKRsCBYbloJn_iYP70-ZUhOXi7870CYesIT5SNeYHsxFU4rQ==

    volumes:
      - ./api-gateway-auth/src:/root/src
    ports:
      - 8000:3000
    depends_on:
      - redis
      - identity-service
      - device-mgnt
      - front-end

  front-end:
    build:
      dockerfile: test.dockerfile
      context: ./iot-app/
    image: guilhermeroque/iot-app-test
    environment:
      - REACT_APP_API_GATEWAY=http://localhost:8000/api
      - REACT_APP_APP_ENV=local
    ports:
      - "8080:3000"
    volumes:
      - ./iot-app/src:/root/src

  identity-service:
    build:
      dockerfile: test.dockerfile
      context: ./auth-service/
    image: guilhermeroque/auth-service-test
    environment:
      - DB_URL=mongodb://mongo/
      - DB_NAME=identity-service
      - DB_USERNAME=lorawanMgnt-admin
      - DB_PASSWORD=lorawanMgnt-admin
      - DB_HOST=mongo
      - SERVER_PORT=3000
      - SWAGGER_HOST=localhost:3000
      - ACCESS_TOKEN_SECRET=45d239dd6d20d8e4c5919079a40e5ea6cf8d9ab0
      - REFRESH_TOKEN_SECRET=45d239dd6d20d8e4c5919079a40e5ea6cf8d9ab0
      - ACCESS_TOKEN_TIMEOUT=300s
      - REFRESH_TOKEN_TIMEOUT=1d
      - APP_ENV=local
    volumes:
      - ./auth-service/src:/root/src
    ports:
      - "3000:3000"
    depends_on:
      - mongo

  device-mgnt:
    build:
      dockerfile: test.dockerfile
      context: ./device-mgnt
    image: guilhermeroque/device-mgnt
    environment:
      - BROKER_TTN=eu1.cloud.thethings.network
      - PORT_TTN=1883
      - PASSWORD_TTN=NNSXS.4UEYPLW2ZI765HTJSQSKEUSV3XCZ3UBTFRF3XNA.JR3QGULLZVMS5HYA2AHY47XRJQTDKCJ3IPTLRLJ7I7UO2K2QPZAA
      - USER_TTN=lorawan-mgnt
      - EMAIL_TTN=guilherme.lr@aluno.ifsc.edu.br
      - DB_URL=mongodb://mongo/
      - DB_NAME=device-mgnt
      - DB_USERNAME=lorawanMgnt-admin
      - DB_PASSWORD=lorawanMgnt-admin
      - DB_HOST=mongo
      - SERVER_PORT=3000
      - APP_ENV=local
      - WS_PORT=5000
    ports:
      - "3333:3000"
      - "5000:5000"
    depends_on:
      - influxdb
      - mongo
    volumes:
      - ./device-mgnt/src:/root/src

  redis: 
    image: redis:7.0.4
    ports:
      - "6379:6379"
      
  mongo:
    image: mongo:5.0-focal
    environment:
      - MONGO_INITDB_ROOT_USERNAME=lorawanMgnt-admin
      - MONGO_INITDB_ROOT_PASSWORD=lorawanMgnt-admin
    ports:
      - "27017:27017"

  influxdb:
    image: influxdb:2.3.0
    environment: 
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=lorawanMgnt-admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=lorawanMgnt-admin
      - DOCKER_INFLUXDB_INIT_ORG=lorawanMgnt-org
      - DOCKER_INFLUXDB_INIT_BUCKET=lorawanMgnt-bucket
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=8s7p1LY3SSGWX-yH2UAKPKABloCcH2s3MwWr71sKRsCBYbloJn_iYP70-ZUhOXi7870CYesIT5SNeYHsxFU4rQ==
    volumes:
      - ./influxdb2:/var/lib/influxdb2:rw
    ports:
      - "8086:8086"


