version: '3'
services:
  front-end:
    build:
      dockerfile: test.dockerfile
      context: ./iot-app/
    image: guilhermeroque/iot-app-test
    environment:
      - REACT_APP_IDENTITY_SERVER=http://localhost:3000
    ports:
      - "8080:3000"
    volumes:
      - ./iot-app/src:/root/src
    depends_on:
      - identity-service

  identity-service:
    build:
      dockerfile: test.dockerfile
      context: ./auth-service/
    image: guilhermeroque/auth-service-test
    environment:
      - DB_URL=mongodb://mongo/
      - DB_NAME=auth-service
      - DB_USERNAME=myUserAdmin
      - DB_PASSWORD=password
      - DB_HOST=mongo
      - SERVER_PORT=3000
      - SWAGGER_HOST=localhost:3000
    volumes:
      - ./auth-service/src:/root/src
    ports:
      - "3000:3000"
    depends_on:
      - mongo

  mongo:
    build:
      dockerfile: ./auth-service/mongodb.dockerfile
      context: .
    image: guilhermeroque/mongodb-test
    ports:
      - "27017:27017"